log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

  flower:
    address: ":5555"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "paul@cybertowel.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    api-secure-router:
      rule: 'Host(`{{env "DOMAIN_NAME"}}`) && PathPrefix(`/webui`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: open-webui
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    jupyter-secure-router:
      rule: 'Host(`{{env "DOMAIN_NAME"}}`) && PathPrefix(`/jupyter`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: jupyter
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    jupyter:
      loadBalancer:
        servers:
          - url: http://jupyter:5000

    ollama-webui:
      loadBalancer:
        servers:
          - url: http://ollama:8000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
